@startuml

hide empty members
skinparam linetype polyline

title "Generator Format"

interface MeshGenerator {
    + generate(mesh: Mesh)
    + getWidth(): int
    + getHeight(): int
}

class AbstractMeshGenerator {
    - verticesThickness: float
    - segmentsThickness: float
    - width: int
    - height: int
    - vertexColorGenerator: ColorGenerator
    - segmentColorGenerator: ColorGenerator
    - polygonColorGenerator: ColorGenerator
    ---
    # this(generators: ColorGenerator[], thickness: float[], dimensions: int[])
    ---
    # getVerticesThickness(): float
    # getSegmentsThickness(): float
    # getVertexColorGenerator(): ColorGenerator
    # getSegmentColorGenerator(): ColorGenerator
    # getPolygonColorGenerator(): ColorGenerator
}

class GridMeshGenerator {
    - squareSize: double
    ---
    + this(generators: ColorGenerator[], thickness: float[], dimensions: int[], squareSize: double)
}

class IrregularMeshGenerator {
    - numPolygons: int
    - mesh: JTSMesh
    - voronoi: VoronoiDiagram
    - relaxation: LloydRelaxation
    ---
    + this(generators: ColorGenerator[], thickness: float[], dimensions: int[], relaxationLevel: int, numPolygons: int)
}

interface ColorGenerator<T extends Colorable> {
    generateColor(colorable: T)
}

class RandomColorGenerator {}
class SetColorGenerator {
    - color: java.awt.Color
    ---
    + this(color: java.awt.Color)
}
class SegmentColorGenerator {}
class PolygonSegmentColorGenerator {}
class PolygonVertexColorGenerator {}
class PolygonTransparentColorGenerator {}

AbstractMeshGenerator -[dashed]-> MeshGenerator
GridMeshGenerator -[dashed]-> AbstractMeshGenerator
IrregularMeshGenerator -[dashed]-> AbstractMeshGenerator

AbstractMeshGenerator *--> "3" ColorGenerator

ColorGenerator <-[dashed]- RandomColorGenerator
ColorGenerator <-[dashed]- SetColorGenerator
ColorGenerator <-[dashed]- SegmentColorGenerator
ColorGenerator <-[dashed]- PolygonVertexColorGenerator
ColorGenerator <-[dashed]- PolygonSegmentColorGenerator
ColorGenerator <-[dashed]- PolygonTransparentColorGenerator

newpage
title "Generator Options Format"

class Option {}

class ColorOption {}
class MeshDimensionOption {}
class MeshTypeOption {}
class NumberPolygonsOption {}
class RelaxationLevelOption {}
class SquareSizeOption {}
class ThicknessOption {}

class GeneratorInputHandler {
    {static} GENERATOR_OPTIONS: Map<String, Option>
    ---
    {static} getGeneratorOption(opt: String): Option
    {static} getInputHandler(args: String): InputHandler
    {static} getThickness(handler: InputHandler): float[]
    {static} getMeshGenerator(handler: InputHandler): MeshGenerator
    {static} getMeshDimensions(handler: InputHandler): int[]
    {static} getGridMeshSquareSize(handler: InputHandler): double
    {static} getColorGenerator(handler: InputHandler): ColorGenerator[]
    {static} getRelaxationLevel(handler: InputHandler): int
    {static} getNumPolygons(handler: InputHandler): int
}

Option <-[dashed]- ColorOption
Option <-[dashed]- MeshDimensionOption
Option <-[dashed]- MeshTypeOption
Option <-[dashed]- NumberPolygonsOption
Option <-[dashed]- RelaxationLevelOption
Option <-[dashed]- SquareSizeOption
Option <-[dashed]- ThicknessOption

ColorOption             "1" <--*        GeneratorInputHandler
MeshDimensionOption     "1" <--*        GeneratorInputHandler
MeshTypeOption          "1" <--*        GeneratorInputHandler
NumberPolygonsOption    "1" <--*        GeneratorInputHandler
RelaxationLevelOption   "1" <--*        GeneratorInputHandler
SquareSizeOption        "1" <--*        GeneratorInputHandler
ThicknessOption         "1" <--*        GeneratorInputHandler

newpage
title "Geometry Class Format"

class JTSMesh {
    - jtsPolygons: List<org.locationtech.jts.geom.Polygo>
    - vertices: Vertices
    - segments: Segments
    - polygons: Polygons
    ---
    + putPolygons(polygons: List<org.locationtech.jts.geom.Polygon>)
    + getPolygons(): List<org.locationtech.jts.geom.Polygon>
    + getConverted(): Mesh
}

class VoronoiDiagram {
    - voronoi: VoronoiDiagramBuilder
    - envelope: Envelope
    ---
    + this(width: int, height: int)
    ---
    + generateDiagram(coordinates: List<Coordinate>, precision: double): List<org.locationtech.jts.geom.Polygon>
    + reset()
}

class LloydRelaxation {
    - relaxationLevel: int
    - voronoi: VoronoiDiagram
    ---
    this(voronoi: VoronoiDiagram, relaxationLevel: int)
    ---
    + apply(polygons: List<org.locationtech.jts.geom.Polygon>)): List<org.locationtech.jts.geom.Polygon>
}

class PolygonNeighborFinder {
    - polygons: List<Polygon>
    ---
    + this(polygons: List<Polygon>)
    ---
    + findNeighbors(): Map<Polygon, List<Polygon>>
}

VoronoiDiagram             "1" <--*        LloydRelaxation

@enduml